"""Add messages model

Revision ID: 5ce758b34c5a
Revises: 38498c1e5da2
Create Date: 2023-11-24 22:51:31.884141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce758b34c5a'
down_revision = '38498c1e5da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
